package only_gary.controller;

import only_gary.model.User;
import only_gary.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    //Return user with userId
    @GetMapping(path="/getById")
    public @ResponseBody User getUserById(@RequestParam int id) {
        User n = userRepository.findById(id);
        if (n != null) {
            return n;
        }
        return null;
    }

    //Return user with userName
    @GetMapping(path="/getByUsername")
    public @ResponseBody User getUserByUsername(@RequestParam String username) {
        User n = userRepository.findByUsername(username);
        if (n != null) {
            return n;
        }
        return null;
    }

    //Return all users
    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        return userRepository.findAll();
    }

}